### ISSUE TITLE
Add Caching On Travis Builds

### ISSUE THREAD

**Issue by alexfinnarn** [AmpedRadio/alexa-streaming-php#9]
Adding caching should speed up the builds.

```yaml
cache:
  directories:
    - $HOME/.composer/cache/files
```

References:
- https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
- https://docs.travis-ci.com/user/caching/
